### ISSUE TITLE
Provide copy of all messages shown in the WordPress plugin

### ISSUE THREAD

**Issue by mnikolovski** [EmitKnowledge/Envoice.WP#10]
Can you please provide us with all of the messages that are shown after an action is completed(Ex: Successfully saved) so we can update them?

Thank you.

**Comment by dorogoff** [comment]
Settings page (api key/secret)
`Settings were saved!`

Products page, when you click copy embed/checkout button
`Successfully copied to clipboard`

Seems it's all copies that we have for notifications.
